### ISSUE TITLE
Clear incomplete states when a user navigates away from a view.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#117]
When a users starts changing their password, abandons and navigates away, when they return, the state has not changed. Should we clear the state on backwards navigation?

## GIF

![Screen Capture on 2023-04-20 at 10-32-18](https://user-images.githubusercontent.com/1657336/233235103-d24b123a-7392-4310-907f-17a9d1979b88.gif)

**Comment by StevenDufresne** [comment]
This apparently worked but no longer does:

https://github.com/WordPress/wporg-two-factor/blob/aae7ec97a9a8ee22342476f2e0bc78ac3ff4aa3c/settings/src/script.js#L99

**Comment by outdoor2kode** [comment]
I guess it does work, the reason password wasn't clear after `edit( record )` is probably due to it's undefined at the start. 
Adding something like `userRecord.record.password = '';` to the start of `password.js` could potentially solve it, but some handles for the isPasswordStrong notice are still needed.

![Screen Shot 2023-04-20 at 12 19 55 PM](https://user-images.githubusercontent.com/18050944/233257193-dc3ac13b-ed1e-4106-a07e-8b53ee910991.png)

![Screen Capture on 2023-04-20 at 12-26-39](https://user-images.githubusercontent.com/18050944/233258131-02055963-e24e-48ba-9ed1-9a9d8cfb374d.gif)

**Comment by iandunn** [comment]
Re-opening because I think this was accidentally closed by this part of the #121 description:

> This doesn't close https://github.com/WordPress/wporg-two-factor/issues/117 as the password view still dirty regardless of the navigation back and forth.

The `... close #117 ...` bit gets read out of context and treated the same as `Closes #117` on its own line would be.

**Comment by outdoor2kode** [comment]
TODO: Clear `password` inputs after navigating away from its setting view.
