### ISSUE TITLE
If the password is changed, 2fa can't be disabled 

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#191]
A revalidation modal should be prompted.

![pwd changed can't disable 2fa](https://github.com/WordPress/wporg-two-factor/assets/18050944/92c53e55-0856-4f71-a9e1-ed8b5add2397)

**Comment by pkevan** [comment]
Presumably the session becomes invalid upon password change, so we'd need to handle that?

**Comment by dd32** [comment]
> Presumably the session becomes invalid upon password change

It turns out that upon the password being changed, an entirely new session is started, which lacks any custom session metadata.

But the page response / REST API response occurs in the context of the OLD session, not the new one, so the data that the REST-API responds with is valid, just not the session data that the users future HTTP requests involve.

https://github.com/WordPress/wordpress-develop/blob/e82251df5bd59fb4327d0b0aa7a57ade20fe97c2/src/wp-includes/user.php#L2717-L2735

This is partially a core bug, that Two-Factor needs to take into account (unfortunately), we can probably work-around it on WordPress.org, but I'm not sure we should try. I'll put together an upstream core bug, and then two-factor bug.

**Comment by dd32** [comment]
> This is partially a core bug,

https://core.trac.wordpress.org/ticket/58427 + https://github.com/WordPress/wordpress-develop/pull/4522

> that Two-Factor needs to take into account (unfortunately)

https://github.com/WordPress/two-factor/issues/573 + https://github.com/WordPress/two-factor/pull/574

If the upstream PR doesn't land, we can also use this:
```php
/**
 * Sync the session two-factor details to newly created sessions for the user.
 *
 * @see https://core.trac.wordpress.org/ticket/58427
 * @see https://github.com/WordPress/two-factor/issues/573
 */
add_filter( 'attach_session_information', static function( $session, $user_id ) {
	if ( $user_id === get_current_user_id() ) {
		$session = array_merge( $session, Two_Factor_Core::get_current_user_session() );
	}

	return $session;
}, 10, 2 );
```

**Comment by StevenDufresne** [comment]
@dd32 Is this worth adding seeing that the patch hasn't landed?

**Comment by dd32** [comment]
@StevenDufresne Is this still a problem? Seeing as https://github.com/WordPress/two-factor/pull/574 has landed it should workaround the core patch that hasn't landed.  I think this might be able to be closed as fixed..

**Comment by StevenDufresne** [comment]
Seems to be working.
