### ISSUE TITLE
Make 2fa settings easier to find.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#220]
Up until this point, we have given beta testers the link to go directly to their 2fa settings. 

Have we considered the best path into the settings yet?

**Comment by iandunn** [comment]
https://github.com/WordPress/wordpress.org/pull/114 will add the `Edit Account` link to the menu for everyone rather than just beta testers. I'm guessing we'll want to finish the WebAuthn UI and some other stuff before doing that though.

Folks who are required to have 2FA will see the notification banner too. That's a small group right now, but #6 would expand it a bit.

I can see us wanting some more ways beyond that, but don't have any immediate ideas.

**Comment by StevenDufresne** [comment]
> https://github.com/WordPress/wordpress.org/pull/114 will add the Edit Account link to the menu for everyone rather than just beta testers. I'm guessing we'll want to finish the WebAuthn UI and some other stuff before doing that though.

Ah, thanks. I looked through this repository and didn't find anything. 👍 

> Folks who are required to have 2FA will see the notification banner too

Yeah, let's coordinate with marketing when we get webauthn out.

**Comment by iandunn** [comment]
https://github.com/WordPress/wordpress.org/pull/114 is done now, so I think the only thing left here is the marketing
