### ISSUE TITLE
Move Account settings on to separate screen

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#26]
> I think it would make sense to split the "Account" subsection that has Email/Password onto a new tab, and list that along with 2FA on that page.
> https://github.com/WordPress/wporg-two-factor/issues/15#issuecomment-1316376334

Breaking this off of #15 since it's a distinct task, and something that needs to be done in the `wporg-support` theme.

- [x] Create new Edit Account screen at https://wordpress.org/support/users/me/edit/account/
- [x] Populate screen with custom UI
- [x] Update Rosetta forums with same changes as main forums
- [x] Move Account settings from https://wordpress.org/support/users/me/edit/ to new screen -- staged in https://github.com/WordPress/wordpress.org/pull/114 but needs to wait until we launch for all users. Or maybe move it all to Profiles instread? Will still need to have the password/lang/etc settings removed from forums, unless ignoring them for now.
- [x] Update `Your password can be changed via...` link on `https://profiles.wordpress.org/{username}/profile/edit/group/1/` -- `wp-content/themes/profiles.wordpress.org/members/single/profile/edit-custom-general.php`

**Comment by dd32** [comment]
FYI; If we're splitting the "Account details" onto a new tab in bbPress (Which I didn't think we were going to do, MVP and all) then we'll also need to take into account Rosetta forums where these details can be managed too: https://fr.wordpress.org/support/users/profile/edit/

If we're creating a whole new Email/Password UI in addition to the 2FA UI then we might as well move it to profiles.w.org, since there's very little dependency upon bbPress then..
The main reason for me saying profiles was a no-go was that we'd have to create our own Email/Password UI in addition to the 2FA UI. We can come back to this discussion later though, as the JS will work on either page.

**Comment by iandunn** [comment]
🤔 ah, ok, i didn't realize that was the reason. Given that, it does seem like moving straight to Profiles would be ideal, if there's time.

The main reason that I included password/etc was that it felt like the screen would be very disjointed if it was a mix of the bbPress UI and our custom UI. Maybe that's not really a concern though, if it won't be shown to users until its polished, which would give us time to move it to Profiles?

**Comment by iandunn** [comment]
Done in `r12896-meta` and `r20932-dotorg`
