### ISSUE TITLE
Reauth 2nd factor to change 2FA settings

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#43]
There's [an upstream issue for this](https://github.com/WordPress/two-factor/issues/484), but we'll probably need to do our own since we have the custom UI.

**Comment by dd32** [comment]
I've started work upstream in https://github.com/WordPress/two-factor/pull/529 but there's a major catch - I've used WordPress sessions upstream, and WordPress.org doesn't support those.

In some brief testing, I believe that we can likely use WordPress Sessions on WordPress.org as well, there's some hacky-hackery that we could use to make WordPress see sessions, but have Trac/Codex use non-sessioned cookies. Either that, or just fix those to also use sessions finally.. I've [done some work on Trac support](https://github.com/dd32/TracWordPressCookiesPlugin/compare/migrate/sessions) already.

**Comment by StevenDufresne** [comment]
Can we narrow down the focus of this ticket? Maybe generated a specific to-do list?

**Comment by dd32** [comment]
@StevenDufresne Sure
 - Reauth 2FA tokens when changing 2FA details.
   - Prompt user if it's been >xx mins since last 2FA challenge before displaying UI.

Dependencies:
 - Upstream https://github.com/WordPress/two-factor/pull/529
   - Which depends upon https://github.com/WordPress/two-factor/pull/528
 - WordPress Sessions
   - Wordress.org requires https://make.wordpress.org/systems/2023/03/09/upgrade-tracwpcookies-plugin/ before Sessions can be enabled

The dependencies are completed, but need testing, merging and/or systems.
