### ISSUE TITLE
Update Instances of 'Two Factor' to be 'Two-Factor'

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-two-factor#49]
For consistency, let's update all instances of 'Two Factor' to 'Two-Factor' across the plugin. Here's where I'm seeing it:

'Disable Two Factor' button:
<img width="1012" alt="Screenshot 2023-02-01 at 11 49 26 AM" src="https://user-images.githubusercontent.com/7133400/216108124-6ffd65e7-29af-4315-9cd0-344bde493951.png">

On the same screen, we are calling two-factor authentication 'Two-step authentication'. Should this be changed for consistency? eg `Status: Two-step authentication is currently on.`

Also on that screen, we refer to two-factor authentication as 'One time passwords' (see the screenshot below for the message when 2fa is disabled). I'd think we should also be consistent with this labeling unless there's a reason not to.

<img width="803" alt="Screenshot 2023-02-01 at 11 53 19 AM" src="https://user-images.githubusercontent.com/7133400/216109272-dbc35ccd-0d5e-4bb2-8678-180108ac9868.png">

'Two Factor Authentication' section link:
<img width="1044" alt="Screenshot 2023-02-01 at 11 49 57 AM" src="https://user-images.githubusercontent.com/7133400/216108255-2bad5cb4-0f79-47f2-a4c5-935f05c2cb14.png">

**Comment by iandunn** [comment]
> update all instances of 'Two Factor' to 'Two-Factor' 

I did that, except for references to [the Two Factor plugin](https://github.com/WordPress/two-factor/) proper, which doesn't hyphenate it.

> we are calling two-factor authentication 'Two-step authentication'

Good catch, that was copy-pasta from the WPCOM design.

> we refer to two-factor authentication as 'One time passwords'

That was intentional, since we're planning to add a WebAuthn provider soonish. At that point there'll be an extra screen, so the UI might look something like:

![Screenshot 2023-02-01 at 10 36 19 AM](https://user-images.githubusercontent.com/484068/216132415-38111732-5cc7-491e-b5fe-215934774abe.png)

...or maybe we'd keep a single Two Factor Authentication link at the top menu, and that screen would display WebAuthn, TOTP, and Backup Codes? It's not really clear yet.

The `One Time Password` name helped to give users some insight into what _form_ of 2FA they had enabled, rather than a generic label. I can see the case for making it consistent for now, though. We can address it later when we add WebAuthn.
