### ISSUE TITLE
Get design review on UI and UX

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#5]
Having a designer review the UI and flows would help refine them, and decrease confusion for setup/recovery/etc. Google has a nice wizard when setting up hardware keys; that might provide some inspiration.

This should probably be broken into multiple tickets once a design is made. Ideally we'd contribute improvements upstream, to improve the plugin for everyone, and also because building a custom UI could lead to vulns in the future when upstream code changes.

IIRC @jeffpaul was also looking into this, so it'd be good to coordinate with him.

Related:
* https://github.com/WordPress/two-factor/pull/261
* https://github.com/WordPress/two-factor/issues/483
* https://github.com/WordPress/two-factor/issues/159
* https://github.com/WordPress/two-factor/issues/486
* https://github.com/WordPress/two-factor/issues/485

**Comment by iandunn** [comment]
One question will be where should the settings live? Probably not `wp-admin`, so maybe w.org/support or profiles.w.org. I'm guessing the login flows would integrate w/ the login.w.org theme.

**Comment by dd32** [comment]
Just uploading a video to show where it's at right now. This _did_ require a change to the upstream plugin, [which I've PR'd](https://github.com/WordPress/two-factor/pull/495).

https://user-images.githubusercontent.com/767313/202323069-fd0d57ba-9f8a-4612-8441-e07e537f7758.mov

Some notable things, some of which need taking upstream to two-factor, some of which will probably want to be changed on WordPress.org-only.
 - It integrates with login easy enough, but the text will likely need updating IMHO.
 - The UX of enabling TOTP, having to also Check the Enable button, and also specify which should be the primary is not ideal. We probably want to hard-code a priority order for WordPress.org (AuthN, TOTP, Backup code)
 - The UX of enabling Backup codes is bad, as shown in the video, I generated and downloaded the codes. **But I did not enable Backup Codes for usage**. As a result, I was unable to use them until I enabled it later.
 - The plugin has some code that assumes it's running within wp-admin, as seen with the TOTP reset process.
 - After TOTP is reset, it may be assumed by some that 2FA has been disabled. If they have Backup codes enabled though, 2FA is still enabled, just with Backup as primary login auth.
 - _Unrelated to this, you'll also spot I couldn't logout from the forums because the logout link in the user-menu was off the screen :)_
 - _Note: Any 2FA shown in this video has already been rotated, and can't be used. All data within the video is public knowledge._

**Comment by tellyworth** [comment]
Yeah that activation flow definitely has to change for w.org. It shouldn't be presented as distinct settings to enable, but as a single flow: scan the QR code, generate your backup codes, confirm a backup code.

**Comment by iandunn** [comment]
I think the user should still be able to choose which providers they want to use, though. That doesn't matter in practice right now, since there's only two -- and Backup Codes is only suitable as a secondary provider -- but WebAuthn will be available in the future.

**Comment by iandunn** [comment]
@WordPress/meta-design, in this repo we're working on [adding two factor authentication to wordpress.org](https://make.wordpress.org/meta/2022/12/22/two-factor-auth-progress-for-wordpress-org/). Joen suggested we base the design on WPCOM, so we're working off of that (see #18 for some screenshots). We've changed things a little bit to fit w.org, but not too much.

We're getting close to launching the MVP, and I think the UI is ready for review. Does anyone have time for that? If so, let me know and I can add you to the beta testers list. That will let you play around with it live on wordpress.org (preferably with a test account, but you can use your real one if you want). Just let me know which account you want to use and I'll set that up and show you where to go etc.

**Comment by jeffpaul** [comment]
While not in meta-design myself, I'm open to help test as well as improving this flow is a long-standing irk I have with the plugin that I would :1000000000: :looooooove: to see happen.

**Comment by iandunn** [comment]
Thanks! 👍🏻 You should be able to see it now, by going to `https://wordpress.org/support/users/{ your username }/edit/account/`

The UI is a bit tailored to w.org, so it's on the front end, and includes the email/password fields. I don't think there are any big barriers to adapting it for the plugin/wp-admin, though. The code is in is in https://github.com/WordPress/wporg-two-factor/tree/trunk/settings

Let me know what you think!

**Comment by jasmussen** [comment]
Thank you for the ping. Would it be possible to see a video of the flow like Dion shared earlier? That might be an easy light weight way to provide feedback. Otherwise, I should have username `Joen` and would be happy to test when I get a moment.

**Comment by iandunn** [comment]
No problem:

https://user-images.githubusercontent.com/484068/216478073-afc81ffa-fce7-42bd-802d-c2355ac4fa76.mov

**Comment by jasmussen** [comment]
Thank you, that's incredibly useful! Let me give a ton of feedback, just to track it here, but I don't know that we need all of this addressed for the first version — some of the feedback I'll give is likely going to be related to the larger Support forum redesign to come down the line. So I'll also refer to your input on what is useful to implement first.

<img width="1430" alt="Screenshot 2023-02-03 at 10 34 43" src="https://user-images.githubusercontent.com/1204802/216566068-4988c661-7554-4bfc-88b7-e3aabf279660.png">

- [x] Thanks for reusing the language bar from the homepage here, it looks appropriate. But I wonder if we can make the linked text longer than "enable it"? Could the entire last sentence starting with "You cannot" be linked?

<img width="987" alt="Screenshot 2023-02-03 at 10 35 06" src="https://user-images.githubusercontent.com/1204802/216566439-0cf2bb50-5b71-465d-a326-7b7dbc7643c2.png">

Generally works well. Thanks for using the new icon set. It also looks like you are using the colors from the library:
<img width="969" alt="Screenshot 2023-02-03 at 10 41 16" src="https://user-images.githubusercontent.com/1204802/216566772-f18a80d0-4c65-43e0-b88f-b09ee29c29d6.png">

- [ ] This is more of a note to @WordPress/meta-design, that these colors are becoming obsolete and could use an update across block editor and WordPress.org alike. Most probably we can lean into these two explored alternatives:
<img width="937" alt="Screenshot 2023-02-03 at 10 41 21" src="https://user-images.githubusercontent.com/1204802/216566887-096d52e0-6f6c-44ad-8a27-abed474d91c8.png">

<img width="827" alt="Screenshot 2023-02-03 at 10 35 22" src="https://user-images.githubusercontent.com/1204802/216566997-1db35557-cec2-4882-95f8-1cd02c4b0b55.png">

- [x] Should the "Show password" icon be inside the input field? At least visually? That makes it feel more connected to the action, the fact that it reveals the password. 

- [x] We should also have a toggled state for this icon. Here are two options:
<img width="874" alt="Screenshot 2023-02-03 at 10 50 45" src="https://user-images.githubusercontent.com/1204802/216568811-a47e627c-3012-42e4-ac3c-2b3398a8d703.png">

Any preference? Let me know and I'll provide the SVGs.

On a separate note, the [block editor is moving towards 40px inputs and buttons by default](https://github.com/WordPress/gutenberg/issues/46734):
<img width="996" alt="Screenshot 2023-02-03 at 10 52 25" src="https://user-images.githubusercontent.com/1204802/216569193-b5c9bd4e-fe4f-4097-a365-5a39a6824cfe.png">

- [ ] Would be nice to reuse that pattern here and across, since the componentry is already so close.

<img width="122" alt="Screenshot 2023-02-03 at 10 35 28" src="https://user-images.githubusercontent.com/1204802/216569423-6fa78f37-f4ff-4699-805f-4f0a10d54951.png">

- [x] Instead of the arrow, the Chevron icon is probably a better fit. I'd also make both icon and text the same color / part of the same link. You may also be able to use the chevron alone.

Small detail, the focus style here is a bit awkward. 
<img width="120" alt="Screenshot 2023-02-03 at 10 36 20" src="https://user-images.githubusercontent.com/1204802/216570074-bd731728-7ad1-45ca-800b-5922751c609d.png">

- [x] I suspect it could be square if the icon sat inside the input.

<img width="884" alt="Screenshot 2023-02-03 at 10 36 34" src="https://user-images.githubusercontent.com/1204802/216570164-1fe5272f-00c9-43b2-971f-68568b2024a9.png">

The "Generate strong password" also untoggles the "hide password". Which I suppose makes sense, otherwise you wouldn't know what a strong password looks like. But it reinforces the idea that we need a visible toggle state for the eye, such as the icon change.

<img width="887" alt="Screenshot 2023-02-03 at 10 36 03" src="https://user-images.githubusercontent.com/1204802/216570363-081d12da-062a-422f-9657-a404fde8d064.png">

This one is a bit awkward in layout. I'm also not convinced that notice needs to be red. Block editor specific, sure, but [this PR](https://github.com/WordPress/gutenberg/pull/47670) adds a different visual treatment for the notice, which I think would work well here:

<img width="324" alt="Screenshot 2023-02-03 at 10 59 13" src="https://user-images.githubusercontent.com/1204802/216570735-a89ca95d-8a69-4065-9a20-4ec647a3c5b3.png">

- [x] This snackbar pushes the content down.

<img width="960" alt="Screenshot 2023-02-03 at 10 59 41" src="https://user-images.githubusercontent.com/1204802/216570842-a12b6a4c-5d2e-46e0-b844-d99c8dd34e1f.png">

It's also a bit confusing that you remain on the "password" page and have to click "back". I would expect to be taken to a new step in the wizard that says "Password changed", with a "Done" or "Okay" button that then takes me to the main security checkup screen again.

<img width="566" alt="Screenshot 2023-02-03 at 11 01 56" src="https://user-images.githubusercontent.com/1204802/216571310-33830f7e-9582-42c0-8d8d-77c660813b20.png">

- [x] Can we show those numbers larger? Perhaps in the IBM Plex Mono font that's used in some other places on the new design? Okay to postpone this change since it's not yet touching the larger refresh.

- [x] Layoutwise, this is also a bit packed together. We may want to split into two steps. One step for the intro:

<img width="815" alt="2fa step 1" src="https://user-images.githubusercontent.com/1204802/216575827-1f36c4bf-fd3b-4104-ad84-ff025c3f9dbd.png">

And one step for the non-QR code version:

<img width="815" alt="2fa step 2" src="https://user-images.githubusercontent.com/1204802/216575842-0224fccb-4244-4828-be05-9e4d50958f5a.png">

Another for the text version:

<img width="815" alt="2fa step 2b" src="https://user-images.githubusercontent.com/1204802/216575868-96e2a0e7-6c27-48c8-bb21-525ff21b09a2.png">

Hope that's useful!

**Comment by beafialho** [comment]
- [ ] I agree with everything suggested by @jasmussen! Just wanted to add that there are some new [callout](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=1264%3A4116&t=J84RGsBZiKyY1Svp-4) layouts that can be reused, with new colors in the WordPress.org Library:

<img width="897" alt="Captura de ecrã 2023-02-03, às 10 30 27" src="https://user-images.githubusercontent.com/65220155/216578970-d945be33-a8da-4e7b-abd4-8f0c15c034c4.png">

**Comment by iandunn** [comment]
> Could the entire last sentence starting with "You cannot" be linked?

I agree that "enable it" is too short to stand out visually, and "it" is vague for screen readers. Linking the entire sentence [slows down screen reader users](https://webaim.org/techniques/hypertext/link_text#text), though, and has a similar effect on sighted users.

More: https://www.nngroup.com/articles/better-link-labels/, https://www.nngroup.com/articles/writing-links/

I've changed it to "Your account requires extra security. Please [enable two-factor authentication](#)", but I think that could probably be refined more. It doesn't explain _why_ the account requires extra security (because it has elevated permissions, maintains a popular plugin, etc), and it doesn't explain that their permissions have been temporarily disabled until they enable 2FA. 

I played around with several variations, but couldn't find anything that communicated everything they need to know without being too verbose. Do you have any thoughts?

**Comment by iandunn** [comment]
>  It also looks like you are using the colors from [`base-styles`]:

Er, it actually wasn't, but I've updated it to use them 👍🏻  I also updated the greys to do the same.

> Instead of the arrow, the Chevron icon is probably a better fit. I'd also make both icon and text the same color / part of the same link.

Done 👍🏻 

> This snackbar pushes the content down.

Good point. It can't just be `position: absolute`, though, because longer messages would overlap the screen title:

![Screenshot 2023-02-03 at 4 24 11 PM](https://user-images.githubusercontent.com/484068/216734540-22fa044d-9dd9-4f60-97a7-e915e85e3a4e.png)

We could move the title to the left, but that wouldn't guarantee that it'd never be overridden. That might be good enough in practice, but it might also look worse on the left. What do you think?

**Comment by jasmussen** [comment]
>  It doesn't explain why the account requires extra security (because it has elevated permissions, maintains a popular plugin, etc), and it doesn't explain that their permissions have been temporarily disabled until they enable 2FA.

I don't know if @WordPress/marketing has bandwidth to look at phrasing, but I imagine they might have ideas.

One of the opportunities for reduction is to put some of that text, i.e. the _why_, on the destination screen instead of the notice.

> We could move the title to the left, but that wouldn't guarantee that it'd never be overridden. That might be good enough in practice, but it might also look worse on the left. What do you think?

Snackbars in general seem to me like they should all be in a consistent fixed place, like button center or bottom left, a la the block editor. But I think there's a simpler question of whether we need a snackbar here at all. When you are successful in enabling one time 2fa, that takes you to a new page already, right? I.e. you see Backup Codes after you are succesful. That way, we could simply weave the confirmation into the prose, rather than snackbar it.

**Comment by iandunn** [comment]
> put some of that text [...] on the destination screen instead of the notice

🤔 I tried that out, but it seems a bit odd having two notices on the same screen that reference each other, but are in separate locations. (ignore the imperfect styles, this is just a rough sketch to illustrate having both on the same screen)

![Screenshot 2023-02-06 at 11 46 15 AM](https://user-images.githubusercontent.com/484068/217069838-8e236d66-51d2-4c62-b218-00316be62ba4.png)

Were you thinking of doing it differently than that?

**Comment by iandunn** [comment]
> weave the confirmation into the prose, rather than snackbar it.

I played around with that it a bit, but didn't get it to where it felt good. I'll circle back to it though. 

In the meantime I was able to got the notice positioned absolutely without covering the title, though:

![Screenshot 2023-02-06 at 11 30 38 AM](https://user-images.githubusercontent.com/484068/217066843-e7d97c05-7563-4712-a78f-f11fdb11c3cb.png)

**Comment by thetinyl** [comment]
> I don't know if https://github.com/orgs/WordPress/teams/marketing has bandwidth to look at phrasing, but I imagine they might have ideas.

Oh hi! 👋 Thought I'd jump in here and see if I can help. 

> It doesn't explain why the account requires extra security (because it has elevated permissions, maintains a popular plugin, etc), and it doesn't explain that their permissions have been temporarily disabled until they enable 2FA.

I can see how this one's a challenge. There's a lot that needs to be understood. Figured I'd offer a first attempt. It's not as short as the two sentences you currently have, but it is shorter than the original shown above:

"Your account has elevated privileges and requires extra security before you can continue. Enable two-factor authentication now."

**Comment by iandunn** [comment]
I like that, thanks!

**Comment by tellyworth** [comment]
Decision needed: what are the blocking issues here needed for the MVP launch?

**Comment by iandunn** [comment]
Some of these are already done, and I think I'll have time to get a few more in before we launch. The launch is just for beta users, so I think it's fine for the rest to get done in the next milestone.

I went ahead and moved it to the next milestone, but LMK if anyone has any objections and we can reconsider.

**Comment by StevenDufresne** [comment]
I think @renintw represented the remaining work in the following issues:

- https://github.com/WordPress/wporg-two-factor/issues/89
- https://github.com/WordPress/wporg-two-factor/issues/88
- https://github.com/WordPress/wporg-two-factor/issues/93
- https://github.com/WordPress/wporg-two-factor/issues/90

If there's nothing else, can we consider closing this ticket or removing it from the MVP milestone?

**Comment by StevenDufresne** [comment]
Alright, closing this, open a new issue if some nuance was missed in the issue extraction. Thanks ya'll!!
